// <auto-generated />
namespace Speedo_Bus_Facilitation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class t51 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t51));
        
        string IMigrationMetadata.Id
        {
            get { return "202206022156598_t51"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
