// <auto-generated />
namespace Speedo_Bus_Facilitation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class t54 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t54));
        
        string IMigrationMetadata.Id
        {
            get { return "202206062055558_t54"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
